name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: make build
